export const measurements = [
    'pound',
    'pounds',
    'clove',
    'cloves',
    'teaspoon',
    'teaspoons',
    'tablespoon',
    'tablespoons',
    'cup',
    'cups',
    'ounce',
    'ounces',
    'fluid ounce',
    'fluid ounces',
    'gallon',
    'gallons',
    'dollop',
    'dollops',
    'slice',
    'slices',
    'half',
    'halves',
    'teacup',
    'teacups',
    'gill',
    'gills',
    'dash',
    'dashes',
    'pint',
    'pints',
    'quart',
    'quarts',
    'pinch',
    'pinches',
    'liter',
    'liters',
    'drop',
    'drops',
]

export const courses = [
    "hors d'ouevre",
    "soup",
    "appetizer",
    "salad",
    "main course",
    "dessert"
]